### ISSUE TITLE
weird selection when trying to select current time

### ISSUE THREAD

**Issue by KraXen72** [diogenesofweb/focus#2]
not a big deal, but this is how it looks:
![image](https://user-images.githubusercontent.com/21956756/221562536-ebd4bef5-ac70-4aff-afda-889559b30493.png)
unless you have a reason (i assume you do though, in that case feel free to close),
i don't see why it couldn't be all in 1 element so it's easily + nicely selectable?
but it's just a small nitpick anyway.

**Comment by diogenesofweb** [comment]
The split into 3 elements is for purely styling purposes. 
Without it, the colon character is visually aligned to the bottom, not the center. 

You may inspect the colon character in devtools, it is a span element with only one CSS declaration transform: translateY(-8px);  , and unchecking it will place the coton at the bottom.
