### ISSUE TITLE
simple timer

### ISSUE THREAD

**Issue by KraXen72** [diogenesofweb/focus#3]
the new simple timer is great, however, there is one bug (that i could find):  
while a timer is running, if you start a new one, the new timer will tick down twice as fast.

**Comment by diogenesofweb** [comment]
Added some changes, setting multiple timers should work now.

**Comment by KraXen72** [comment]
yeye looks pretty good, maybe stack the timers horizontally? seems like a lot of wasted space. idk really
![image](https://github.com/diogenesofweb/focus/assets/21956756/d53caebd-d12d-49a4-bc44-9fada3520f0c)

**Comment by diogenesofweb** [comment]
Agreed. Timers should be placed more compactly, horizontally on top or vertically on left. I’ll do it in the following days.

**Comment by KraXen72** [comment]
sorry for not contributing yet i gave all these suggestions but i didn't code anything. one day hopefully lol.

**Comment by diogenesofweb** [comment]
Suggestions are always welcome.

**Comment by KraXen72** [comment]
it would be also good that if only one timer is running and the pomodoro timer is not running, it would show the timer in page title. if both pomodoro and timer are running, pomodoro is shown.

**Comment by diogenesofweb** [comment]
Updated. 
The first of timers will update page title if pomodoro is inactive
