### ISSUE TITLE
Swich Session squence type

### ISSUE THREAD

**Issue by KraXen72** [diogenesofweb/focus#4]
Hi, i can sucessfully change the session sequence's details in the settings, but how do i select which session i want to use? i cannot find an option for that anywhere. Thanks.

**Comment by diogenesofweb** [comment]
Index page, top left corner below header panel, just click on currently active sequence. It should open <select /> with all available sequences.

**Comment by diogenesofweb** [comment]
Sorry, I messed up the if statement while refactoring. Should work now. Thanks for  the notice!

**Comment by KraXen72** [comment]
thanks, it works now! thanks for your continued support & quick fixing of issues!

**Comment by KraXen72** [comment]
also, good job on using proper commit messages!!
